Repository Dev5Oops/Healthtart, pull requests merged in 2024-10, with the labels that each got.

#3 Gym Aggregate 관련 Controller, Service, Repository 추가, 관리자 기능 (헬스장 추가 기능) 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/CommonException.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/ExceptionDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/GlobalExceptionHandler.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/ResponseDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/aggregate/EquipmentPerGym.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/dto/EquipmentPerGymDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/ExerciseEquipment.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/dto/ExerciseEquipmentDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/Gym.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/request/RequestRegisterGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseRegisterGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/controller/GymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/dto/GymDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/repository/GymRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/service/GymService.java
Labels: enhancement

#12 ✨ 기능 추가 feat(#6, #7) : 헬스장 단 건 조회, 전체 조회 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseFindGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/controller/GymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/service/GymService.java
Labels: enhancement, backend

#14 feat(#13 ): 헬스장 단 건, 전체 조회 테스트 추가
  healthtart/src/test/java/com/dev5ops/healthtart/gym/service/GymServiceTests.java
Labels: backend, test

#17 feat(#15 #16 ): 운동기구 등록, 수정 기능 추가, Gym 관련 코드 일부 수정
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/ExerciseEquipment.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/request/RequestEditEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/request/RequestRegisterEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseEditEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseRegisterEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/dto/ExerciseEquipmentDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/repository/ExerciseEquipmentRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/request/RequestEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/controller/GymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/service/GymService.java
Labels: ♻ refactor, enhancement, backend

#19 feat(#18 ): 운동기구 삭제 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentService.java
Labels: enhancement, backend

#21 feat(#11, #20 ): User 회원가입, User 로그인
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/JwtUtil.java
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/UserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestInsertUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestLoginVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement, backend

#22 fix: 헬스장 등록 테스트 코드 수정
  healthtart/src/test/java/com/dev5ops/healthtart/gym/service/GymServiceTests.java
Labels: ♻ refactor, test

#24 feat(#23): 운동기구 단 건 조회, 전체 조회 기능 추가, CRUD 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseFindEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/service/GymService.java
  healthtart/src/test/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentServiceTests.java
Labels: backend, test

#26 feat(#25 ): 헬스장 별 운동기구 aggregate 관련 기능 추가 이전 세팅 + OneToMany 관련 컬럼 삭제로 인한 수정
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/controller/EquipmentPerGymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/repository/EquipmentPerGymRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymService.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/ExerciseEquipment.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/dto/ExerciseEquipmentDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/Gym.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/dto/GymDTO.java
  healthtart/src/test/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentServiceTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/gym/service/GymServiceTests.java
Labels: ♻ refactor, backend

#27 ♻️ 코드 수정 : OneToMany 관련 컬럼 삭제로 인한 수정
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/controller/EquipmentPerGymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/request/RequestEditEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseEditEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseFindEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseRegisterEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/request/RequestEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseFindGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseRegisterGymVO.java
Labels: ♻ refactor

#34 feat(30,31,32,33): 유저별&날짜별 운동기록 조회 기능, 테스트코드 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: enhancement, backend, test

#36 feat(#35 ): 헬스장 별 운동기구 수정 삭제 기능, 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/aggregate/vo/request/RequestEditEquipmentPerGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/aggregate/vo/response/ResponseEditEquipmentPerGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/controller/EquipmentPerGymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/repository/EquipmentPerGymRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymService.java
  healthtart/src/test/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymServiceTests.java
Labels: enhancement, backend, test

#38 feat(#37 ): 헬스장 별 운동기구 조회 기능, 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/aggregate/vo/response/ResponseFindEquipmentPerGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/controller/EquipmentPerGymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymService.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/aggregate/vo/response/ResponseFindEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseFindGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/controller/GymController.java
  healthtart/src/test/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymServiceTests.java
Labels: enhancement, backend, test

#47 ✨ 기능 추가 : WorkoutPerRoutine/ Routine CRUD 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/controller/RoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/dto/RoutineDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/entity/Routine.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/EditRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/RequestDeleteRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/RequestInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/RequestModifyRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/ResponseDeleteRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/ResponseFindRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/ResponseInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/ResponseModifyRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/repository/RoutineRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/controller/WorkoutPerRoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/dto/WorkoutPerRoutineDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/entity/WorkoutPerRoutine.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/EditWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/RequestDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/RequestInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/RequestModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/ResponseDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/ResponseFindWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/ResponseInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/vo/ResponseModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/repository/WorkoutPerRoutineRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_routine/aggregate/WorkoutRoutine.java
  healthtart/src/test/java/com/dev5ops/healthtart/routine/service/RoutineServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImplTests.java
Labels: bug, enhancement

#48 🐛 오류 수정: RecordPerUserRepository 컬럼 타입 오류 수정
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/aggregate/RecommendedWorkoutHistory.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: bug, enhancement, backend

#50 feat(#49 ): 인바디 등록 기능, 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/request/RequestEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/aggregate/vo/response/ResponseRegisterGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/dto/GymDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/Inbody.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/request/RequestEditInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/request/RequestRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseEditInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseFindInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/dto/InbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/gym/service/GymServiceTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: enhancement, backend, test

#52 feat(#51 ): 인바디 수정 기능, 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: enhancement, backend, test

#55 feat(#53 #54 ): 인바디 삭제, 조회 기능 + 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: enhancement, backend, test

#56 ✨ 기능 추가 : 관리자, 유저 인바디 정보 조회 기능 분리 후 유저용 인바디 조회 기능, 테스트 추가
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: ♻ refactor, enhancement, backend

#57 ✨ 기능 추가: jwt 사용한 로그인, 회원가입 기능 추가
  .idea/.gitignore
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/HealthtartApplication.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/AppConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/HMACKeyGenerator.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtUtil.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/secutiry/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/UserTypeEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/UserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestInsertUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestLogInVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement

#60 ✨ 기능 추가 : 인바디 서비스 수정
  healthtart/.gitignore
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: ♻ refactor

#61 전체적인 코드 수정
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/Inbody.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/request/RequestEditInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/request/RequestRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseEditInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseFindInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/OCRController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/dto/InbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyDataExtractor.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/VisionService.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestLoginUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestLoginVO.java
Labels: bug

#63 ✨ 기능 추가 : OCR을 통해 텍스트를 읽는 방식 수정 완료
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyDataExtractor.java
Labels: enhancement, backend

#67 ✨ 기능 추가: RecordPerUserService CUD 추가
  healthtart/.gitignore
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/vo/request/RequestRegistRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/vo/response/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/dto/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: enhancement, backend

#68 ✨ 기능 추가 : Google Cloud Storage api 를 받아와 이미지 업로드 및 업로드 된 이미지 OCR 구현 완료
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/FileUploadController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/OCRController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/VisionService.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
Labels: enhancement, backend

#71 운동기구에서의 부위 별 운동기구 조회 추가
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/controller/ExerciseEquipmentController.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/repository/ExerciseEquipmentRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentService.java
  healthtart/src/test/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentServiceTests.java
Labels: enhancement, backend, test

#73 ✨ 기능 추가: OpenAI Api 추가 및 callOpenAI 메서드 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/GptConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/openai/controller/GptController.java
  healthtart/src/main/java/com/dev5ops/healthtart/openai/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/vo/request/RequestRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/vo/response/ResponseFindPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/aggregate/vo/response/ResponseRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/controller/RecordPerUserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: enhancement, backend

#78 feat(#74): 일반 유저, OAuth2 유저 로그인, 회원가입 기능 수정
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtUtil.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/OAuth2AuthenticationSuccessHandler.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/CustomUserDetails.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/UserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CustomOAuth2UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement, backend

#77 ✨ 기능 추가: callOpenAI메서드 role-system추가/generatePrompt, generateRoutine메서드 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/entity/RecommendedWorkoutHistory.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/controller/RecordPerUserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/entity/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/request/RequestRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseFindPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/gpt/service/GptServiceTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: enhancement, backend

#76 ✨ 기능 추가 : UserCode를 통해 키, 몸무게, 성별, 나이 조회 후 UserData기반으로 GPT 운동 루틴 추천 Test 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/test/java/com/dev5ops/healthtart/gpt/service/GptServiceTests.java
Labels: enhancement

#79 🔥 코드 수정: GptService 의존성 주입 방식 변경/주석 삭제
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/request/RequestRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/repository/RecommendedWorkoutHistoryRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryService.java
Labels: ♻ refactor, enhancement, backend

#82 feat(#81) 유저 조회 및 탈퇴
  .github/ISSUE_TEMPLATE/기능-개발-템플릿.md
  .github/ISSUE_TEMPLATE/리팩터링-템플릿.md
  .github/pull_request_template.md
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement, backend

#83 feat(#81) ResponseFindUserVO 추가
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/response/ResponseFindUserVO.java
Labels: backend

#85 ✨ 기능 추가 : Routine , WorkoutPerRoutine 테스트 기능 추가 및 구조 리팩토링
  healthtart/src/main/java/com/dev5ops/healthtart/routine/controller/RoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestDeleteRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestModifyRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/response/ResponseDeleteRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/response/ResponseFindRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/response/ResponseInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/response/ResponseModifyRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/controller/WorkoutPerRoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/entity/WorkoutPerRoutine.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/EditWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseFindWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/repository/WorkoutPerRoutineRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/routine/service/RoutineServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImplTests.java
Labels: enhancement

#84 feat(#80): Rival 조회, 등록, 삭제 기능 구현
  healthtart/src/main/java/com/dev5ops/healthtart/rival/controller/RivalController.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/dto/RivalDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/dto/RivalUserInbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/dto/RivalUserInbodyScoreDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/entity/Rival.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/vo/request/RequestInsertRivalVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/vo/response/ResponseInsertRivalVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/repository/RivalRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/service/RivalService.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/service/RivalServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/inbody/UserInbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
Labels: bug, enhancement, backend

#88 ✨ 기능 추가: RecommendedWorkoutHistoryController 만족도 등록 controller 추가
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/controller/RecommendedWorkoutHistoryController.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/entity/RecommendedWorkoutHistory.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/request/RequestRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseFindByRatingOrderVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryService.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/controller/RecordPerUserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/entity/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/request/RequestRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseFindPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/repository/RecordPerUserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: enhancement, backend

#90 ✨ 기능 추가: Dockerfile 추가 및 ingree설정 기능 추가
  healthtart/Dockerfile
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/WebConfig.java
  healthtart_front/Dockerfile
  healthtart_front/nginx.conf
Labels: enhancement

#91 ✨ 기능 추가 / 수정: k8s manifest 파일 추가
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CustomOAuth2UserService.java
  healthtart_k8s_manifests/healthtart_boot_dep.yml
  healthtart_k8s_manifests/healthtart_boot_ser.yml
  healthtart_k8s_manifests/healthtart_ingress.yml
  healthtart_k8s_manifests/healthtart_vue_dep.yml
  healthtart_k8s_manifests/healthtart_vue_ser.yml
Labels: enhancement, backend, frontend

#94 ✨ 기능 추가 : 메인페이지에 Header 적용
  healthtart_front/package-lock.json
  healthtart_front/package.json
  healthtart_front/src/App.vue
  healthtart_front/src/assets/css/Main/MainPage.css
  healthtart_front/src/views/MainPage.vue
Labels: enhancement, frontend

#95 ♻️ 코드 수정: AppHeader 수정
  healthtart_front/src/assets/icons/logo.svg
  healthtart_front/src/components/AppHeader.vue
Labels: enhancement, frontend

#97 ♻️ 코드 수정: 회원가입 시 UserTypeEnum이 기본적으로 MEMBER가 되도록 수정
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/WebConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestInsertUserVO.java
Labels: ♻ refactor, backend

#98 feat(#57) jwt를 활용한 로그인 프론트 연동 성공 및 데이터 교환 성공
  healthtart/src/main/java/com/dev5ops/healthtart/TestController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtUtil.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/JwtTokenDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/UserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestLoginVO.java
Labels: bug, ♻ refactor, enhancement, backend

#101 ✨ 기능 추가: GptServiceImpl에 routineParser 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
  healthtart_front/package-lock.json
  healthtart_front/package.json
  healthtart_front/src/App.vue
  healthtart_front/src/assets/css/Main/MainPage.css
  healthtart_front/src/components/routine/RoutineInnerTab.vue
  healthtart_front/src/router/router.js
  healthtart_front/src/router/routine.js
  healthtart_front/src/views/routine/WorkoutInfoInputPage.vue
Labels: enhancement, backend

#102 feat(#58) OAuth2 유저 프론트 회원가입, 로그인 연동 성공
  healthtart/src/main/java/com/dev5ops/healthtart/security/AuthenticationFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/OAuth2AuthenticationSuccessHandler.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestOauth2VO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CustomOAuth2UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: bug, enhancement, backend, frontend

#104 ✨ 기능 추가: WorkoutPerRoutineService - checkForDuplicateRoutines 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/repository/WorkoutPerRoutineRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
Labels: enhancement, backend

#108 ✨ 기능 추가/수정 : 헬스장, 운동기구 관련 권한 추가, 헬스장 별 운동기구 중복 등록 시 예외처리 추가, 관련 엔티티 LocalDateTime 포맷 추가, 특정 헬스장 내 부위 별 운동기구 조회로 변경
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/controller/EquipmentPerGymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/domain/entity/EquipmentPerGym.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/domain/vo/response/ResponseEditEquipmentPerGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/domain/vo/response/ResponseRegisterEquipmentPerGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/repository/EquipmentPerGymRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymService.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/domain/entity/ExerciseEquipment.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/domain/vo/response/ResponseEditEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/domain/vo/response/ResponseRegisterEquipmentVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/domain/entity/Gym.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/domain/vo/response/ResponseEditGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/domain/vo/response/ResponseRegisterGymVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/test/java/com/dev5ops/healthtart/equipment_per_gym/service/EquipmentPerGymServiceTests.java
Labels: enhancement, backend

#110 feat(#109): SMTP, Redis 추가
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/EmailConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/RedisConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/GoogleUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/ResponseEmailDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/inbody/UserInbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/EmailVerificationVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/ResponseEmailMessageVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/EmailVerificationService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: bug, enhancement, backend

#113 인바디 api 호출 시 반환되는 데이터 형태 수정, WebSecurity api 권한 추가 및 수정
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/Inbody.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/request/RequestRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseEditInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseFindInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseRegisterInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/dto/InbodyDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyDataExtractor.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
Labels: enhancement, backend

#114 ♻️ 코드 수정: 오류 수정
  healthtart/src/main/java/com/dev5ops/healthtart/security/OAuth2AuthenticationSuccessHandler.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestOauth2VO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CustomOAuth2UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement

#116 WebSecurity 설정
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
Labels: enhancement

#117 ✨ 기능 추가 : GptService 유저 정보와 헬스기구 정보를 통한 GPT 루틴 생성 후 3개 도메인에 저장 테스트 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/exercise_equipment/service/ExerciseEquipmentService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/repository/RecommendedWorkoutHistoryRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/controller/RoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/entity/Routine.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestDeleteRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/response/ResponseInsertRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/dto/WorkoutPerRoutineDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/entity/WorkoutPerRoutine.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/EditWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/request/RequestModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseDeleteWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseFindWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseInsertWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseModifyWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/repository/WorkoutPerRoutineRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/dto/WorkoutInfoDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/entity/WorkoutInfo.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/request/RequestDeleteWorkoutInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/request/RequestInsertWorkoutInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/response/ResponseDeleteWorkoutInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/response/ResponseFindWorkoutInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/response/ResponseInsertWorkoutInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/gpt/service/GptServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/routine/service/RoutineServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoServiceImplTests.java
Labels: enhancement

#118 ✨ 기능 추가/수정 : 인바디 서비스 코드 수정으로 인해 테스트 코드 수정
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/aggregate/vo/response/ResponseFindInbodyVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/controller/InbodyController.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/dto/FilterRequestDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/repository/InbodyRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/inbody/service/InbodyService.java
  healthtart/src/test/java/com/dev5ops/healthtart/inbody/service/InbodyServiceTests.java
Labels: ♻ refactor, enhancement, backend, test

#121 feat(#119, #120): 닉네임, 이메일 중복 방지, 비밀번호 재설정
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestResetPasswordVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement, backend

#122 ✨ 기능 추가: GptService, Controller 수정
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/controller/GptController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
Labels: enhancement, backend

#124 ✨ 기능 추가 : RecommendedWorkoutHistory 운동루틴 코드별 운동추천내역 관련 Test 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/controller/RecommendedWorkoutHistoryController.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/entity/RecommendedWorkoutHistory.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/request/RequestRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseFindByRatingOrderVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryService.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryServiceImplTests.java
Labels: ♻ refactor, enhancement

#125 ✨ 코드 수정: RecommendedWorkoutHistory setter추가 및 코드 수정
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/controller/RecommendedWorkoutHistoryController.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/domain/vo/response/ResponseFindWorkoutInfoVO.java
Labels: enhancement, backend

#123 User, Gym, Rival 컨트롤러 서비스 리포지토리 수정 및 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/controller/GptController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/domain/entity/Gym.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/controller/RivalController.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/dto/RivalDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/domain/vo/response/ResponseRivalVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/repository/RivalRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/service/RivalService.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/service/RivalServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/EditMypageDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/dto/EditPasswordDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RegisterGymPerUserRequest.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestEditMypageVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestEditPasswordVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/response/ResponseEditMypageVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/response/ResponseEditPasswordVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: ♻ refactor, enhancement, backend

#126 ✨ 기능 추가 / 수정: 비밀번호 재설정(resetPassword) 기능 추가 및 유저 부분 코드 리팩토링
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/WebConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/StatusEnum.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CustomOAuth2UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: backend

#127 ✨ 기능 추가 : findWorkoutPerRoutineByCode루틴 코드별 운동루틴별 운동 단일 조회 기능 추가
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/controller/WorkoutPerRoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/controller/WorkoutInfoController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoServiceImpl.java
Labels: enhancement

#128 기능 추가/수정 : Patch API 요청할 수 있게 수정 및 editPassword 메소드 수정
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: ♻ refactor, enhancement, backend

#129 ♻️ 코드 수정: WorkoutPerRoutineController, Service, ServiceImpl 타입 변경
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/controller/WorkoutPerRoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseFindWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/service/WorkoutPerRoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/controller/WorkoutInfoController.java
Labels: enhancement, backend

#132 ✨ 기능 추가 / 수정: User, Rival 테스트코드 작성
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/rival/service/RivalServiceImplTests.java
  healthtart/src/test/java/com/dev5ops/healthtart/user/service/UserServiceImplTests.java
Labels: enhancement, backend, test

#134 ✨ 기능 추가: SMS 인증 기능 추가
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/CoolSmsConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/common/exception/CoolSmsException.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/entity/UserEntity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/EmailRequestVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/SmsVerificationRequestVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CoolSmsService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement, backend

#136 ✨ 기능 추가 / 수정: Swagger Config 설정 완료
  healthtart/build.gradle
  healthtart/src/main/java/com/dev5ops/healthtart/common/config/SwaggerConfig.java
  healthtart/src/main/java/com/dev5ops/healthtart/rival/controller/RivalController.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/JwtFilter.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: documentation, enhancement, backend

#137 ♻️ 코드 수정: CoolSMS 예외처리 로직 수정
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/repository/UserRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/CoolSmsService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: bug, backend

#138 유저 키, 몸무게 정보 수정 api 추가
  healthtart/src/main/java/com/dev5ops/healthtart/user/controller/UserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/domain/vo/request/RequestUserInfoVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: enhancement

#141 ♻️ 코드 수정: 운동 루틴 삭제 코드 수정
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/controller/GptController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptService.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/service/GptServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/controller/RecordPerUserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/entity/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/request/RequestRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/controller/RoutineController.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/domain/vo/request/RequestModifyRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineService.java
  healthtart/src/main/java/com/dev5ops/healthtart/routine/service/RoutineServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/user/service/UserServiceImplTests.java
Labels: enhancement, backend

#142 ♻️ 코드 수정: signUpUser 반환형 수정
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/user/service/UserServiceImpl.java
Labels: bug

#143 ✨ 기능 추가 : 사업자 등록번호로 헬스장 조회
  healthtart/src/main/java/com/dev5ops/healthtart/gym/controller/GymController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gym/service/GymService.java
Labels: enhancement, backend

#145 ✨ 기능 추가 : 운동 루틴 생성, 재생성 코드 추가
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/controller/GptController.java
  healthtart/src/main/java/com/dev5ops/healthtart/gpt/domain/vo/RequestRegisterRoutineVO.java
Labels: enhancement, backend

#146 ✨ 기능 수정 : 운동 기록 테스트 기능 수정
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/controller/RecommendedWorkoutHistoryController.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/request/RequestRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseFindByRatingOrderVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/vo/response/ResponseRegisterRecommendedWorkoutHistoryVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/repository/RecommendedWorkoutHistoryRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/controller/RecordPerUserController.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/dto/RecordPerUserDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/entity/RecordPerUser.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/request/RequestRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseFindPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/domain/vo/vo/response/ResponseRegisterRecordPerUserVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workout_per_routine/domain/vo/response/ResponseFindWorkoutPerRoutineVO.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/controller/WorkoutInfoController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/repository/WorkoutInfoRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoServiceImpl.java
  healthtart/src/test/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserServiceTests.java
Labels: bug, ♻ refactor, enhancement

#147 ✨ 기능 변경: 만족도 계산 기능 변경
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/controller/RecommendedWorkoutHistoryController.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/dto/RecommendedWorkoutHistoryDTO.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/domain/entity/RecommendedWorkoutHistory.java
  healthtart/src/main/java/com/dev5ops/healthtart/recommended_workout_history/service/RecommendedWorkoutHistoryServiceImpl.java
  healthtart/src/main/java/com/dev5ops/healthtart/record_per_user/service/RecordPerUserService.java
  healthtart/src/main/java/com/dev5ops/healthtart/security/WebSecurity.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/controller/WorkoutInfoController.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/repository/WorkoutInfoRepository.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoService.java
  healthtart/src/main/java/com/dev5ops/healthtart/workoutinfo/service/WorkoutInfoServiceImpl.java
Labels: bug, enhancement, backend
